sudo: required
dist: trusty
language: generic
matrix:
  fast_finish: true

env:
  - TEST_RUN="bash -n archlinux/archlinux-install.sh"
  - TEST_RUN="bash ubuntu/ubuntugnome-install.sh"

script: "$TEST_RUN"

notifications:
  email: False
